---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ls-algorithm-image-analyzer
spec:
  selector:
    matchLabels:
      app: ls-algorithm-image-analyzer
  template:
    metadata:
      labels:
        app: ls-algorithm-image-analyzer
    spec:
      serviceAccountName: scaler-service-account
      containers:
        - name: ls-algorithm
          image: giovaz94/tea-store-ls
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7001
          env:
            - name: SLEEP_TIME
              value: "10"
            - name: MCL
              value: "231"
            - name: COMPONENT_MF
              value: "1.5"
            - name: K_BIG
              value: "10"
            - name: K
              value: "5"
            - name: IN_CLUSTER
              value: "true"
            - name: PROMETHEUS_SERVICE_ADDRESS
              value: "prometheus-service.monitoring"
            - name: PROMETHEUS_SERVICE_PORT
              value: "8080"
            - name: MANIFEST_NAME
              value: "image-analyzer"
            - name: METRIC_NAME
              value: "http_requests_total_image_analyzer_counter"
            - name: SERVICE_PORT
              value: "7001"
            
---
apiVersion: v1
kind: Service
metadata:
  name: ls-algorithm-image-analyzer-service
spec:
  selector:
    app: ls-algorithm-image-analyzer
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
