apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: giovaz94/mail-pipeline-general
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MCL
              value: "110"
            - name: REDIS_HOST
              value: "redis-service"
            - name: SERVICE_NAME
              value: "parser"
            - name: PORT
              value: "80"
            - name: MAX_SIZE
              value: "800"
            - name: VIRUS_SCANNER
              value: "http://virus-scanner-service/request"
            - name: HEADER_ANALYZER
              value: "http://header-analyzer-service/request"
            - name: TEXT_ANALYZER
              value: "http://text-analyzer-service/request"
            - name: LINK_ANALYZER
              value: "http://link-analyzer-service/request"
            - name: MAX_CONNECTIONS
              value: "70"
            - name: PIPELINE_COUNT
              value: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: parser-service
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"   # optional, defaults to /metrics
spec:
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: parser-service
spec:
  host: parser-service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: parser-service
spec:
  hosts:
    - parser-service
  http:
    - route:
        - destination:
            host: parser-service
