apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-virus-scanner-
  labels:
    app: virus-scanner
spec:
  #nodeName: testing-cluster-pool-b7x6c
  containers:
  - name: virus-scanner
    image: giovaz94/mail-pipeline-general
    env:
      - name: MCL
        value: "120"
      - name: REDIS_HOST
        value: "redis-service"
      - name: SERVICE_NAME
        value: "virus-scanner"
      - name: PORT
        value: "80"
      - name: MAX_SIZE
        value: "800"
      - name: MESSAGE_ANALYZER
        value: "http://message-analyzer-service/request"
      - name: ATTACHMENT_MANAGER
        value: "http://attachment-manager-service/request"
      - name: MAX_CONNECTIONS
        value: "70"
      - name: PIPELINE_COUNT
        value: "1"