apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-attachment-manager-
  labels:
    app: attachment-manager
spec:
  #nodeName: testing-cluster-pool-b7x6u
  containers:
  - name: attachment-manager
    image: giovaz94/mail-pipeline-general
    env:
      - name: MCL
        value: "231"
      - name: REDIS_HOST
        value: "redis-service"
      - name: SERVICE_NAME
        value: "attachment-manager"
      - name: PORT
        value: "80"
      - name: MAX_SIZE
        value: "800"
      - name: IMAGE_ANALYZER
        value: "http://image-analyzer-service/request"
      - name: MAX_CONNECTIONS
        value: "70"
      - name: PIPELINE_COUNT
        value: "1"

