apiVersion: v1
kind: Pod
metadata:
  generateName: sys-pod-image-analyzer-
  labels:
    app: image-analyzer
spec:
  #nodeName: testing-cluster-pool-b7x6u
  containers:
  - name: image-analyzer
    image: giovaz94/mail-pipeline-general
    env:
      - name: MCL
        value: "231"
      - name: REDIS_HOST
        value: "redis-service"
      - name: SERVICE_NAME
        value: "image-analyzer"
      - name: PORT
        value: "80"
      - name: MAX_SIZE
        value: "800"
      - name: MESSAGE_ANALYZER
        value: "http://message-analyzer-service/request"
      - name: MAX_CONNECTIONS
        value: "70"
      - name: PIPELINE_COUNT
        value: "1"